//@flow

//types for loginReducer
export const AUTHORIZATION_USER: 'AUTHORIZATION_USER' = 'AUTHORIZATION_USER';
export const AUTHORIZATION_SUCC: 'AUTHORIZATION_SUCC' = 'AUTHORIZATION_SUCC';
export const AUTHORIZATION_ERR: 'AUTHORIZATION_ERR' = 'AUTHORIZATION_ERR';

//types for
