export const getDataMessage = () => {
  return {userMessageBase, userInfo};
};
export const setDataMessage = key => {};

const userInfo = {
  name: 'Andrew',
  surname: 'Nahorniy',
  bio: 'Student',
  age: '22',
  avatar: require('../img/UserImage/photo_2019-08-29_10-01-29.jpg'),
};

const userMessageBase = [
  {
    name: 'Natalie',
    surname: 'Wood',
    phone: '(357)-311-0214',
    key: 'b05b07c6-84e0-46c0-8e1f-fe6da8db2aab',
    avatar: require('../img/userContactsImages/0.jpg'),
    messages: [
      '__1__ability',
      '__1__star',
      '__1__hardly',
      '__0__arrangement cross close first fully cause save',
      '__1__dance circus her without railroad',
      '__0__half',
      '__1__seven married mass surrounded already',
      '__1__labor',
      '__0__fireplace cause forgotten carry children sort',
      '__0__family ten largest express smell leaf',
      '__0__within atomic breathing hunter concerned plate',
      '__1__thrown summer matter',
      '__0__indeed brush appearance',
      '__0__importance adult steady mysterious travel account',
      '__0__dig owner spring energy running fort',
      '__1__seems lunch ill recently scared thought',
      '__0__another',
      '__0__satisfied due they pair almost willing',
      '__0__family organization reason political social busy',
      '__1__read public wagon or final garage',
      '__0__grade flat what missing sad shallow',
      '__1__another',
      '__0__base southern first zulu electricity muscle',
      '__1__wheel worse everywhere plastic bar examine',
      '__0__taught sand solve rope mistake especially',
      '__0__rubber',
      '__0__thrown summer matter',
      '__0__indeed brush appearance',
      '__0__spent activity nails sound barn',
      '__1__population',
      '__1__team',
      '__0__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__1__quite library swing high body has left whale answer discuss motor cell',
      '__1__soft throughout rock horn not program search chose wing roar pay package',
      '__1__another',
      '__1__fifty income plan chance why',
      '__0__between',
    ],
  },
  {
    name: 'Rose',
    surname: 'Mitchell',
    phone: '013-440-5359',
    key: '6823c3d3-8a72-4e59-93bc-528023220cb9',
    avatar: require('../img/userContactsImages/1.jpg'),
    messages: [
      '__0__partly become individual bush receive',
      '__0__spent activity nails sound barn',
      '__1__powerful heard seen chair drawn',
      '__0__another',
      '__1__try cheese what result nice either compound layers other column',
      '__0__making hit known basket master few sad careful fall chair',
      '__1__east high thus along barn education breathe huge grew printed',
      '__0__clear is against own forget under evening affect press mood',
      '__0__porch require alone escape spirit',
      '__1__ground dead bigger agree silence',
      '__1__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__1__quite library swing high body has left whale answer discuss motor cell',
      '__1__soft throughout rock horn not program search chose wing roar pay package',
      '__1__seven married mass surrounded already',
      '__1__hundred work lion let dollar',
      '__0__fifty income plan chance why',
      '__0__spend lead flag see compass',
      '__0__wonder education hunter equally story',
      '__1__dance circus her without railroad',
      '__0__thrown summer matter',
      '__0__ride flag wrote motion small',
    ],
  },
  {
    name: 'Juan',
    surname: 'Carrasco',
    phone: '967-926-563',
    key: '487ae582-4b95-46e9-b49e-95fb9ead4a30',
    avatar: require('../img/userContactsImages/2.jpg'),
    messages: [
      '__0__brain deep afraid',
      '__0__hundred work lion let dollar',
      '__0__fed property refused',
      '__0__apartment pupil chart',
      '__0__east dawn list',
      '__0__plural feet troops',
      '__1__stopped under car',
      '__1__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__0__quite library swing high body has left whale answer discuss motor cell',
      '__0__soft throughout rock horn not program search chose wing roar pay package',
      '__0__log kind this',
      '__0__thrown summer matter',
      '__1__indeed brush appearance',
      '__0__tape ants mighty',
      '__0__pipe setting buy',
      '__1__damage silver seven',
      '__1__cat line again',
      '__1__afternoon aloud body',
    ],
  },
  {
    name: 'Mohammad',
    surname: 'Lemm',
    phone: '0833-3802165',
    key: '56c9f8da-8b5d-4b96-bb69-d251c5a7af1a',
    avatar: require('../img/userContactsImages/3.jpg'),
    messages: [
      'including bark egg until rich warn hour',
      'melted mouse develop list husband pupil labor',
      'captain properly stomach pure shoe successful trail',
      'indeed brush appearance',
      'military teach opposite slowly moving particularly spite',
      'slight fifty meat into situation solution whale',
      'thrown summer matter',
      'independent wool desk clear growth fish line slip research ever gasoline mix',
      'quite library swing high body has left whale answer discuss motor cell',
      'soft throughout rock horn not program search chose wing roar pay package',
      'indeed brush appearance',
      'arrangement cross close first fully cause save',
      'bat recent under yet',
      'knew make buffalo bell',
      'star',
      'hardly',
      'quiet itself six memory toy meat general',
      'nine active limited fear shade note desert',
      'star',
      'creature throughout them giant exciting balloon around',
      'remember table lose shells wore creature feathers',
    ],
  },
  {
    name: 'Eduard',
    surname: 'Brunet',
    phone: '076 077 37 25',
    key: 'bbed4c65-afbc-46be-b724-9e421e8492d6',
    avatar: require('../img/userContactsImages/4.jpg'),
    messages: [
      '__0__including bark egg until rich warn hour',
      '__0__melted mouse develop list husband pupil labor',
      '__0__captain properly stomach pure shoe successful trail',
      '__1__indeed brush appearance',
      '__0__military teach opposite slowly moving particularly spite',
      '__1__slight fifty meat into situation solution whale',
      '__1__thrown summer matter',
      '__0__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__0__quite library swing high body has left whale answer discuss motor cell',
      '__0__soft throughout rock horn not program search chose wing roar pay package',
      '__0__indeed brush appearance',
      '__0__arrangement cross close first fully cause save',
      '__1__bat recent under yet',
      '__0__knew make buffalo bell',
      '__1__star',
      '__1__hardly',
      '__0__quiet itself six memory toy meat general',
      '__1__nine active limited fear shade note desert',
      '__0__star',
      '__0__creature throughout them giant exciting balloon around',
      '__0__remember table lose shells wore creature feathers',
    ],
  },
  {
    name: 'Lilja',
    surname: 'Rintala',
    phone: '07-552-704',
    key: 'd1272521-25db-4a29-90e3-280c3283615e',
    avatar: require('../img/userContactsImages/5.jpg'),
    messages: [
      '__0__step kids slept during vapor',
      '__0__rod climate dry late tube',
      '__0__pet shoe corn promised funny',
      '__0__spring bit political touch obtain',
      '__1__sleep unknown north belong breath belong',
      '__0__afternoon team thumb outside island',
      '__0__thrown summer matter',
      '__0__indeed brush appearance',
      '__1__short cold thy single smooth',
      '__1__try cheese what result nice either compound layers other column',
      '__0__making hit known basket master few sad careful fall chair',
      '__0__east high thus along barn education breathe huge grew printed',
      '__1__clear is against own forget under evening affect press mood',
      '__1__include drew lower sweet gone',
      '__1__die became base science native highway plenty village successful suit',
      '__0__watch island master support needs climb open interior choice wish',
      '__0__nose told deep simple winter title bet star chemical silence',
      '__0__support tone school sudden sum slight cell passage took jungle',
      '__1__labor',
      '__0__rubber',
      '__0__thrown summer matter',
      '__1__production make now pleasant',
      '__1__thank atomic program nose',
      '__0__port front universe us such',
      '__0__thrown summer matter',
      '__0__indeed brush appearance',
      '__0__alone girl saw rock make',
      '__0__to arrive chamber moon pull',
    ],
  },
  {
    name: 'Agustin',
    surname: 'Arias',
    phone: '961-114-347',
    key: 'c88e71db-0660-45ae-8f0b-bee89881b2bf',
    avatar: require('../img/userContactsImages/6.jpg'),
    messages: [
      '__1__number threw activity signal fifty leave',
      '__1__basic identity pony living noun addition',
      '__0__part suit my heading allow tone',
      '__1__conversation hope freedom level telephone structure',
      '__1__lose gain steam stove bow bill',
      '__0__base older atmosphere interior funny himself',
      '__0__slip dust recall shinning circus naturally',
      '__1__win best ago hearing paragraph natural',
      '__1__thrown summer matter',
      '__0__indeed brush appearance',
      '__1__would having nine fur smaller unhappy',
      '__0__cry women eat neighbor see map',
      '__0__two smooth hold gulf fourth solve',
      '__1__screen flag unit refused',
      '__1__unless wall forgotten screen declared nation',
      '__0__cut title various thee decide carried',
      '__1__constantly opposite moving tune cave aware',
      '__1__could this congress rhyme major heat',
      '__1__trick poetry somebody whispered town slope',
      '__1__sleep unknown north belong breath belong',
      '__1__art mean bottle late low tube',
      '__0__oxygen been shot per led third',
      '__0__duck strip waste five mouth own',
      '__1__arrangement cross close first fully cause save',
      '__1__dance circus her without railroad',
      '__0__half',
      '__1__seven married mass surrounded already',
      '__0__labor',
      '__0__rubber',
      '__1__thrown summer matter',
      '__1__lion late beauty rhythm put shine',
      '__0__salt happily around low behavior bright',
      '__1__outline grandmother sea white equal man',
      '__0__valley office consist primitive friendly left',
      '__0__goes birth parent increase lesson explain',
      '__0__rise little recently settle national dress',
      '__0__fireplace equator strength this try loss',
      '__1__built grown jet for cup stream',
      '__1__hay porch sail sick require heading',
      '__0__with expect important highway affect printed',
    ],
  },
  {
    name: 'Lucy',
    surname: 'Graham',
    phone: '041-177-0482',
    key: '80f71db1-674a-46aa-b376-f284103810f6',
    avatar: require('../img/userContactsImages/7.jpg'),
    messages: [
      '__0__live teacher fed short',
      '__1__previous third pitch shaking',
      '__1__troops center trace difficult',
      '__1__dance escape been ready',
      '__0__arrangement cross close first fully cause save',
      '__1__dance circus her without railroad',
      '__0__half',
      '__0__seven married mass surrounded already',
      '__0__labor',
      '__0__rubber',
      '__1__thrown summer matter',
      '__1__black ice pale atmosphere',
      '__0__shade married book press',
      '__1__basis together usual flew',
      '__0__according escape color another',
      '__0__stairs citizen actually down',
      '__1__dug scientist them came',
      '__0__around tide off wonderful',
      '__1__use paragraph stand road',
      '__1__knew policeman question expect',
      '__0__whispered every root mass',
      '__0__facing here which except',
      '__0__hand difficulty excited salmon',
      '__1__cap office unhappy swim',
      '__0__outline grandmother sea white equal man',
      '__1__due fierce rhythm drawn',
      '__0__screen flag unit refused',
      '__0__molecular love slowly contrast',
      '__1__early one root color',
      '__1__slide accept nine taken',
      '__0__valuable word decide mine',
      '__1__type definition local powder',
      '__0__card pure people former',
      '__0__railroad element mouse place',
      '__1__sleep unknown north belong breath belong',
      '__0__bat recent under yet',
      '__0__knew make buffalo bell',
      '__1__arrangement cross close first fully cause save',
      '__1__dance circus her without railroad',
      '__1__half',
      '__1__seven married mass surrounded already',
      '__1__labor',
      '__0__rubber',
      '__0__thrown summer matter',
      '__1__production make now pleasant',
      '__1__thank atomic program nose',
    ],
  },
  {
    name: 'Ramna',
    surname: 'Oliveira',
    phone: '(55) 2195-4478',
    key: 'a93853da-529a-4abd-bc95-5e8138502300',
    avatar: require('../img/userContactsImages/8.jpg'),
    messages: [
      '__0__plain quietly chosen page chicken gift return blue clay building',
      '__0__small forget handle flow distance previous count children nuts coming',
      '__0__explanation property massage paragraph throw explore dance discussion look daily',
      '__0__disease real west stretch meant leave badly rabbit solar article',
      '__0__each stiff cup sport many personal want teeth shut shirt',
      '__0__busy tall lake lovely original glad graph theory greater weak',
      '__0__try cheese what result nice either compound layers other column',
      '__0__making hit known basket master few sad careful fall chair',
      '__1__plural feet troops',
      '__1__stopped under car',
      '__1__log kind this',
      '__1__tape ants mighty',
      '__1__east high thus along barn education breathe huge grew printed',
      '__1__clear is against own forget under evening affect press mood',
      '__1__pony sugar mirror wise find attempt smoke upon ourselves company',
      '__0__forward mostly manufacturing return pretty stuck women flower tiny sat',
      '__1__soil original nodded examine nearly identity near arm too exchange',
      '__1__fresh per hundred roar land cook anywhere bush foot rocky',
      '__1__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__1__quite library swing high body has left whale answer discuss motor cell',
      '__0__soft throughout rock horn not program search chose wing roar pay package',
      '__0__sugar various shake sold fireplace disappear sets doctor taught anything',
      '__0__away whole unhappy seems worry wheat wealth rain market doctor',
      '__1__thrown summer matter',
      '__1__indeed brush appearance',
      '__1__six clock negative mice rough touch strength fear slight shout',
      '__1__cook series kind sang see while safe wagon pure cowboy',
      '__0__go go go',
      '__0__rubbed daughter bone today married little well strip love cold',
      '__1__traffic could bus shinning caught sheet bank solar earlier at',
      '__0__die became base science native highway plenty village successful suit',
      '__1__watch island master support needs climb open interior choice wish',
      '__1__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__1__quite library swing high body has left whale answer discuss motor cell',
      '__0__soft throughout rock horn not program search chose wing roar pay package',
      '__0__nose told deep simple winter title bet star chemical silence',
      '__1__support tone school sudden sum slight cell passage took jungle',
      '__0__labor',
      '__1__rubber',
      '__1__thrown summer matter',
      '__1__production make now pleasant',
      '__1__thank atomic program nose',
      '__1__similar push seat stuck determine paint customs environment did today',
      '__0__sunlight remember throughout care courage draw force house stared unhappy',
      '__1__date headed never dark year member law rocket mass product',
      '__0__establish command chair likely blind disease market distance salt chief',
      '__0__so several alone foreign captain silent paper dig live heat',
      '__0__pine ought living die seven duty actual were belong husband',
      '__0__satisfied due they pair almost willing',
      '__1__family organization reason political social busy',
      '__1__read public wagon or final garage',
      '__1__grade flat what missing sad shallow',
      '__1__another',
    ],
  },
  {
    name: 'Mikkel',
    surname: 'Vanvik',
    phone: '24122946',
    key: '5cf63310-eecf-4553-a306-5a8bf7c9f404',
    avatar: require('../img/userContactsImages/9.jpg'),
    messages: [
      '__1__row mile fed note common offer alike allow numeral brief burn swept',
      '__1__forgot planned leather improve point loose blood distance early reach wind group',
      '__1__development does sang faster loud poet roof crowd large stood language teeth',
      '__1__sign partly cloud result beauty difficult pack scale halfway warn row fewer',
      '__0__independent wool desk clear growth fish line slip research ever gasoline mix',
      '__0__quite library swing high body has left whale answer discuss motor cell',
      '__0__soft throughout rock horn not program search chose wing roar pay package',
      '__1__gold fence complex applied section fight variety failed tank frame select feature',
      '__0__next birds vapor minute soft sense guide little alive open triangle creature',
      '__0__forgotten dead popular measure middle ground work review queen gain nobody cap',
      '__1__pour function dress love appearance trip indicate youth paper hollow vast rubber',
      '__0__provide minerals made keep locate spite could thy sheet riding gentle gun',
      '__1__brick chair fourth born supper waste death ear determine tales compare worry',
      '__0__army loud serious vapor dream physical think chamber enter function hair cover',
      '__1__brass exist smoke sweet flower break wrapped fast pot air tall rose',
      '__1__stuck else lying machine long seven audience increase country fun disease hard',
      '__1__half',
      '__0__seven married mass surrounded already',
      '__1__labor',
      '__1__fireplace cause forgotten carry children sort',
      '__0__family ten largest express smell leaf',
      '__0__within atomic breathing hunter concerned plate',
      '__0__thrown summer matter',
      '__0__indeed brush appearance',
      '__0__importance adult steady mysterious travel account',
      '__0__dig owner spring energy running fort',
      '__1__seems lunch ill recently scared thought',
      '__0__another',
      '__0__satisfied due they pair almost willing',
      '__1__family organization reason political social busy',
      '__0__read public wagon or final garage',
      '__0__grade flat what missing sad shallow',
      '__0__another',
      '__0__base southern first zulu electricity muscle',
      '__0__wheel worse everywhere plastic bar examine',
      '__1__taught sand solve rope mistake especially',
      '__0__rubber',
      '__0__thrown summer matter',
      '__1__indeed brush appearance',
      '__0__spent activity nails sound barn',
      '__0__population',
      '__1__team',
      '__1__dawn army far spider dollar track dry shoulder outer native paragraph football',
      '__1__foreign finish begun owner outer rose distance carry other ball word remarkable',
      '__1__claws free operation wealth tree win medicine ought somehow increase while advice',
      '__0__theory captain street from sometime magnet giving beautiful wing method everywhere belt',
      '__0__powerful matter kept raw school equally entire writing continued straight game corn',
      '__0__sentence teacher blue grass bring prepare boat silk rubber how colony plates',
      '__0__however pictured belong final dropped tail half native vessels faster comfortable few',
      '__0__chapter shells stone hall contrast fairly nearer machine curve greatest gun view',
      '__1__swing rubbed just use glass bus tomorrow breeze caught drew six spread',
      '__0__ability',
      '__0__birds',
      '__0__plate',
      '__1__tightly',
      '__0__prepare',
    ],
  },
  {
    name: 'Agenor',
    surname: 'Pereira',
    phone: '(61) 9814-9553',
    key: '53697b1c-58e2-4968-bb26-fbe24d20b7c2',
    avatar: require('../img/userContactsImages/10.jpg'),
    messages: [
      '__0__in',
      '__1__scared',
      '__1__shake',
      '__0__tide',
      '__0__bag',
      '__0__strike',
      '__1__finally',
      '__1__season',
      '__1__stick further enjoy finger seems happen gravi…rful fine them sky laugh long ship magic southern',
      '__1__thirty laugh hunt bag balloon brave observe p…my discuss income ask shut greatly bean flat tide',
      '__0__theory captain street from sometime magnet giving beautiful wing method everywhere belt',
      '__0__powerful matter kept raw school equally entire writing continued straight game corn',
      '__1__sentence teacher blue grass bring prepare boat silk rubber how colony plates',
      '__0__trade',
      '__1__pot',
      '__0__pain',
      '__0__ability',
      '__1__birds',
      '__1__plate',
      '__1__tightly',
      '__1__prepare',
      '__1__source',
      '__0__stay',
      '__0__theory captain street from sometime magnet giving beautiful wing method everywhere belt',
      '__1__powerful matter kept raw school equally entire writing continued straight game corn',
      '__1__sentence teacher blue grass bring prepare boat silk rubber how colony plates',
      '__0__trade',
      '__1__now',
      '__1__sets',
      '__0__strong',
      '__1__place',
      '__0__so several alone foreign captain silent paper dig live heat',
      '__0__pine ought living die seven duty actual were belong husband',
      '__0__satisfied due they pair almost willing',
      '__0__family organization reason political social busy',
      '__0__read public wagon or final garage',
      '__1__grade flat what missing sad shallow',
      '__1__another',
      '__1__me',
      '__1__club',
      '__0__notice',
    ],
  },
  {
    name: 'Inmaculada',
    surname: 'Morales',
    phone: '985-532-460',
    key: 'c6c9b575-fbcf-4e17-883d-652ef5af3fca',
    avatar: require('../img/userContactsImages/11.jpg'),
    messages: [
      '__0__production worse property pay nearest badly s…essful increase lack vote game somebody old teeth',
      '__0__find nose degree wrapped ready dead pleasant …hen chart ran cow camp step duty wonder soft then',
      '__1__steel also slept pride broke rather usually n…e station sometime flower ago very coat love busy',
      '__0__hold club traffic pull earlier listen other s…irit do eye shoe stood compare board blew unusual',
      '__1__family organization reason political social busy',
      '__1__read public wagon or final garage',
      '__0__grade flat what missing sad shallow',
      '__0__another',
      '__1__world wish column full test name able equally…e spin cover stopped quietly experiment dull each',
      '__1__trunk lonely trick attached effort mouse fact…d loud rose suppose swept hello spin shelf plates',
      '__1__stick further enjoy finger seems happen gravi…rful fine them sky laugh long ship magic southern',
      '__0__thirty laugh hunt bag balloon brave observe p…my discuss income ask shut greatly bean flat tide',
      '__1__theory captain street from sometime magnet giving beautiful wing method everywhere belt',
      '__1__powerful matter kept raw school equally entire writing continued straight game corn',
      '__1__sentence teacher blue grass bring prepare boat silk rubber how colony plates',
      '__1__trade',
      '__1__sets',
      '__0__damage took just heading religious must imagi…ed door brother fresh cow driven claws enter bell',
      '__0__tree actually put single doubt brought additi…ove whole soon happened angle month basket useful',
      '__0__now',
      '__0__column twice strong of teach alphabet childre…t gas design page oxygen donkey quick proud state',
      '__1__outside tip range fly baby plane gun damage m…l birthday value image selection paint skill bill',
      '__1__welcome journey dust poet agree cattle simply…mooth grass somehow curious off second individual',
      '__1__camera through interior welcome tax planning …er voyage tightly fireplace solid share able trap',
      '__0__living recall please any somebody suppose sco…prove camera scale out myself student supply skin',
    ],
  },
];
